import{generateExplanation,callGemini,callWorkersAI,getSystemPrompt,getUserPrompt}from"./ai.js";
const MAX_TEXT_LENGTH=12000,MIN_TEXT_LENGTH=50,MAX_TITLE_LENGTH=200,MIN_TITLE_LENGTH=5,MAX_AUTHOR_LENGTH=100,MIN_AUTHOR_LENGTH=2,MAX_TAGS=20,MAX_TAG_LENGTH=60,RATE_LIMIT_MAX=5,RATE_LIMIT_WINDOW_SECONDS=60;
const JSON_HEADERS={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};

export default{async fetch(request,env,ctx){
 const url=new URL(request.url);
 if(request.method==="OPTIONS")return handleCorsPreflight(request,env);
 try{
  if(!getAllowedOrigin(request,env))return jsonError("Origin is not allowed.",403,request,env);
  if(url.pathname==="/api/explain"){if(request.method!=="POST")return methodNotAllowed(["POST"],request,env);return handleExplain(request,env,ctx);}
  if(url.pathname==="/api/publish"){if(request.method!=="POST")return methodNotAllowed(["POST"],request,env);return handlePublish(request,env,ctx);}
  if(url.pathname==="/api/papers"&&request.method==="GET")return handlePapers(request,env);
  if(url.pathname.startsWith("/api/papers/")){const slug=decodeURIComponent(url.pathname.slice(13));if(request.method==="GET")return handleSinglePaper(request,env,slug);if(request.method==="DELETE")return handleDeletePaper(request,env,ctx,slug);return methodNotAllowed(["GET","DELETE"],request,env);}
  if(url.pathname==="/api/tags"&&request.method==="GET")return handleTags(request,env);
  if(url.pathname.startsWith("/api/tags/"))return request.method==="GET"?handleTag(request,env,decodeURIComponent(url.pathname.slice(10))):methodNotAllowed(["GET"],request,env);
  if(url.pathname.startsWith("/api/authors/"))return request.method==="GET"?handleAuthor(request,env,decodeURIComponent(url.pathname.slice(13))):methodNotAllowed(["GET"],request,env);
  if(url.pathname==="/api/search"&&request.method==="GET")return handleSearch(request,env);
  if(url.pathname==="/api/stats"&&request.method==="GET")return handleStats(request,env);
  if(url.pathname==="/api/explain-test"&&request.method==="POST")return handleExplainTest(request,env,ctx);
  return jsonError("Route not found.",404,request,env);
 }catch(error){ctx.waitUntil(logError(env,request,error,url.pathname,"system"));return jsonError("An unexpected server error occurred.",500,request,env);}
}};

async function handleExplain(req,env,ctx){const rl=await enforceRateLimit(req,env);if(!rl.allowed)return jsonError("Too many requests. Please try again later.",429,req,env,{"Retry-After":rl.retryAfter});const body=await readJsonBody(req,env,ctx,"/api/explain");if(!body.ok)return body.response;const v=validateExplainInput(body.data);if(!v.valid)return jsonError(v.error,400,req,env);const r=await generateExplanation(v.text,v.lang,env,ctx);if(r.fatal){ctx.waitUntil(logError(env,req,new Error("Both AI providers failed."),"/api/explain","none"));return jsonResponse({error:"All AI services are temporarily unavailable. Please try again in a moment.",errors:r.errors,fatal:true},503,req,env);}return jsonResponse({explanation:r.text,provider:r.provider,model:r.model,usedFallback:Boolean(r.usedFallback),latencyMs:r.totalLatencyMs,errors:r.errors||[]},200,req,env);}
async function handlePublish(req,env,ctx){const body=await readJsonBody(req,env,ctx,"/api/publish");if(!body.ok)return body.response;const v=validatePublishInput(body.data);if(!v.valid)return jsonError(v.error,400,req,env);const slug=await createUniqueSlug(env.DB,v.title),authorSlug=slugify(v.author),tags=[...new Set(v.tags)];try{await env.DB.prepare("INSERT INTO authors(name,slug,count) VALUES(?,?,0) ON CONFLICT(slug) DO UPDATE SET name=excluded.name").bind(v.author,authorSlug).run();for(const tag of tags){const s=slugify(tag);await env.DB.prepare("INSERT INTO tags(name,slug,count) VALUES(?,?,0) ON CONFLICT(slug) DO UPDATE SET name=excluded.name").bind(tag,s).run();}const tagSlugs=tags.map(slugify),wordCount=countWords(v.explanation),readingTime=Math.max(1,Math.ceil(wordCount/200));const paper=await env.DB.prepare("INSERT INTO papers(slug,title,author,author_slug,explanation,source_text,lang,tags,views,word_count,reading_time,ai_provider,published_at,updated_at) VALUES(?,?,?,?,?,?,?, ?,0,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id,slug,title,author,lang,tags,word_count,reading_time,ai_provider,published_at").bind(slug,v.title,v.author,authorSlug,v.explanation,v.sourceText,v.lang,JSON.stringify(tagSlugs),wordCount,readingTime,v.aiProvider).first();return jsonResponse({paper,url:`${env.SITE_URL}/paper.html?slug=${encodeURIComponent(slug)}`},201,req,env);}catch(e){ctx.waitUntil(logError(env,req,e,"/api/publish","system"));return jsonError("Unable to publish the paper.",500,req,env);}}
async function handlePapers(req,env){const u=new URL(req.url),page=parsePositiveInteger(u.searchParams.get("page"),1),limit=Math.min(parsePositiveInteger(u.searchParams.get("limit"),20),50),offset=(page-1)*limit;const[r,c]=await Promise.all([env.DB.prepare("SELECT id,slug,title,author,author_slug,lang,tags,views,word_count,reading_time,ai_provider,published_at,updated_at FROM papers ORDER BY published_at DESC,id DESC LIMIT ? OFFSET ?").bind(limit,offset).all(),env.DB.prepare("SELECT COUNT(*) AS count FROM papers").first()]);const total=Number(c?.count||0);return jsonResponse({papers:r.results.map(normalizePaper),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}},200,req,env);}
async function handleSinglePaper(req,env,slug){if(!isValidSlug(slug))return jsonError("Invalid paper slug.",400,req,env);const p=await env.DB.prepare("UPDATE papers SET views=views+1 WHERE slug=? RETURNING id,slug,title,author,author_slug,explanation,source_text,lang,tags,views,word_count,reading_time,ai_provider,published_at,updated_at").bind(slug).first();return p?jsonResponse({paper:normalizePaper(p)},200,req,env):jsonError("Paper not found.",404,req,env);}
async function handleDeletePaper(req,env,ctx,slug){const a=requireAdmin(req,env);if(!a.valid)return jsonError(a.error,a.status,req,env);if(!isValidSlug(slug))return jsonError("Invalid paper slug.",400,req,env);try{const r=await env.DB.prepare("DELETE FROM papers WHERE slug=?").bind(slug).run();return r.meta?.changes?jsonResponse({deleted:true,slug},200,req,env):jsonError("Paper not found.",404,req,env);}catch(e){ctx.waitUntil(logError(env,req,e,"/api/papers/:slug","system"));return jsonError("Unable to delete the paper.",500,req,env);}}
async function handleTags(req,env){const r=await env.DB.prepare("SELECT id,name,slug,count FROM tags ORDER BY count DESC,name COLLATE NOCASE ASC").all();return jsonResponse({tags:r.results},200,req,env);}
async function handleTag(req,env,slug){if(!isValidSlug(slug))return jsonError("Invalid tag slug.",400,req,env);const tag=await env.DB.prepare("SELECT id,name,slug,count FROM tags WHERE slug=?").bind(slug).first();if(!tag)return jsonError("Tag not found.",404,req,env);const r=await env.DB.prepare("SELECT id,slug,title,author,author_slug,lang,tags,views,word_count,reading_time,ai_provider,published_at,updated_at FROM papers WHERE EXISTS(SELECT 1 FROM json_each(papers.tags) WHERE json_each.value=?) ORDER BY published_at DESC,id DESC").bind(slug).all();return jsonResponse({tag,papers:r.results.map(normalizePaper)},200,req,env);}
async function handleAuthor(req,env,slug){if(!isValidSlug(slug))return jsonError("Invalid author slug.",400,req,env);const author=await env.DB.prepare("SELECT id,name,slug,count FROM authors WHERE slug=?").bind(slug).first();if(!author)return jsonError("Author not found.",404,req,env);const r=await env.DB.prepare("SELECT id,slug,title,author,author_slug,lang,tags,views,word_count,reading_time,ai_provider,published_at,updated_at FROM papers WHERE author_slug=? ORDER BY published_at DESC,id DESC").bind(slug).all();return jsonResponse({author,papers:r.results.map(normalizePaper)},200,req,env);}
async function handleSearch(req,env){const q=(new URL(req.url).searchParams.get("q")||"").trim();if(q.length<2||q.length>200)return jsonError("Search query must contain between 2 and 200 characters.",400,req,env);const m=createFtsQuery(q);if(!m)return jsonResponse({query:q,papers:[]},200,req,env);const r=await env.DB.prepare("SELECT p.id,p.slug,p.title,p.author,p.author_slug,p.lang,p.tags,p.views,p.word_count,p.reading_time,p.ai_provider,p.published_at,p.updated_at,bm25(papers_fts) AS rank FROM papers_fts JOIN papers p ON p.id=papers_fts.rowid WHERE papers_fts MATCH ? ORDER BY rank ASC,p.published_at DESC LIMIT 50").bind(m).all();return jsonResponse({query:q,papers:r.results.map(normalizePaper)},200,req,env);}
async function handleStats(req,env){const a=requireAdmin(req,env);if(!a.valid)return jsonError(a.error,a.status,req,env);const d=new Date().toISOString().slice(0,10);const[p,v,ps,n,g]=await Promise.all([env.DB.prepare("SELECT COUNT(*) AS papers FROM papers").first(),env.DB.prepare("SELECT COALESCE(SUM(views),0) AS views FROM papers").first(),env.KV.get("stats:providers","json"),env.KV.get(`usage:neurons:${d}`,"json"),env.KV.get(`usage:gemini:${d}`,"json")]);return jsonResponse({papers:Number(p?.papers||0),views:Number(v?.views||0),providers:ps||{gemini:{success:0,fail:0},"workers-ai":{success:0,fail:0},lastUpdated:null},neuronsToday:n||{total:0,calls:0},geminiToday:g||{count:0,success:0,fail:0}},200,req,env);}
async function handleExplainTest(req,env,ctx){const a=requireAdmin(req,env);if(!a.valid)return jsonError(a.error,a.status,req,env);const b=await readJsonBody(req,env,ctx,"/api/explain-test");if(!b.ok)return b.response;const v=validateExplainTestInput(b.data);if(!v.valid)return jsonError(v.error,400,req,env);try{const r=v.forceProvider==="gemini"?await callGemini(getSystemPrompt(v.lang),getUserPrompt(v.text,v.lang),env.GEMINI_API_KEY):await callWorkersAI(getSystemPrompt(v.lang),getUserPrompt(v.text,v.lang),env);return jsonResponse({...r,usedFallback:false,errors:[]},200,req,env);}catch(e){ctx.waitUntil(logError(env,req,e,"/api/explain-test",v.forceProvider));return jsonError("Forced provider test failed.",503,req,env,{"X-Provider-Error":sanitizeErrorCode(e)});}}

function validateExplainInput(b){if(!isPlainObject(b))return{valid:false,error:"Request body must be a JSON object."};const text=typeof b.text==="string"?b.text.trim():"",lang=b.lang==="hi"||b.lang==="en"?b.lang:null;if(text.length<50||text.length>12000)return{valid:false,error:"Paper text must contain between 50 and 12000 characters."};if(!lang)return{valid:false,error:'Language must be "hi" or "en".'};return{valid:true,text,lang};}
function validateExplainTestInput(b){const v=validateExplainInput(b);if(!v.valid)return v;if(b.forceProvider!=="gemini"&&b.forceProvider!=="workers-ai")return{valid:false,error:'forceProvider must be "gemini" or "workers-ai".'};return{...v,forceProvider:b.forceProvider};}
function validatePublishInput(b){if(!isPlainObject(b))return{valid:false,error:"Request body must be a JSON object."};const title=norm(b.title),author=norm(b.author),explanation=typeof b.explanation==="string"?b.explanation.trim():"",sourceText=typeof b.sourceText==="string"?b.sourceText.trim():"",lang=b.lang==="hi"||b.lang==="en"?b.lang:null,aiProvider=b.aiProvider==="gemini"||b.aiProvider==="workers-ai"?b.aiProvider:null;if(title.length<5||title.length>200)return{valid:false,error:"Title must contain between 5 and 200 characters."};if(author.length<2||author.length>100)return{valid:false,error:"Author must contain between 2 and 100 characters."};if(!explanation)return{valid:false,error:"Explanation is required."};if(sourceText.length<50||sourceText.length>12000)return{valid:false,error:"Source text must contain between 50 and 12000 characters."};if(!lang||!aiProvider||!Array.isArray(b.tags)||b.tags.length>20)return{valid:false,error:"Invalid publish fields."};const tags=[];for(const x of b.tags){if(typeof x!=="string"||x.trim().length<1||x.trim().length>60)return{valid:false,error:"Invalid tag."};tags.push(x.trim());}return{valid:true,title,author,tags,explanation,sourceText,lang,aiProvider};}
async function enforceRateLimit(req,env){if(!env.KV)return{allowed:false,retryAfter:60};const fp=await sha256(`${getClientIp(req)}|${env.SITE_NAME||"paper-explainer"}`),key=`rate:explain:${fp}`,now=Date.now(),old=await env.KV.get(key,"json"),ws=Number(old?.windowStart||now);let count=Number(old?.count||0);if(now-ws>=60000)count=0;if(count>=5)return{allowed:false,retryAfter:Math.max(1,Math.ceil((60000-(now-ws))/1000))};await env.KV.put(key,JSON.stringify({count:count+1,windowStart:count===0||now-ws>=60000?now:ws}),{expirationTtl:60});return{allowed:true,retryAfter:0};}
async function readJsonBody(req,env,ctx,endpoint){if(!(req.headers.get("content-type")||"").toLowerCase().includes("application/json"))return{ok:false,response:jsonError("Content-Type must be application/json.",415,req,env)};try{return{ok:true,data:await req.json()};}catch(e){ctx.waitUntil(logError(env,req,e,endpoint,"system"));return{ok:false,response:jsonError("Invalid JSON request body.",400,req,env)};}}
function requireAdmin(req,env){const h=req.headers.get("Authorization")||"";if(!h.startsWith("Bearer "))return{valid:false,status:401,error:"Authorization is required."};const s=h.slice(7).trim();if(!s||!env.ADMIN_TOKEN)return{valid:false,status:401,error:"Invalid authorization."};return constantTimeEqual(s,env.ADMIN_TOKEN)?{valid:true}:{valid:false,status:403,error:"Invalid authorization."};}
function getAllowedOrigin(req,env){const c=(env.ALLOWED_ORIGIN||"").trim(),o=req.headers.get("Origin");return!o?c:o===c?o:null;}
function handleCorsPreflight(req,env){const o=getAllowedOrigin(req,env);return o?new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":o,"Access-Control-Allow-Methods":"GET, POST, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Max-Age":"86400",Vary:"Origin"}}):new Response(null,{status:403});}
function jsonResponse(data,status,req,env,extra={}){const h=new Headers(JSON_HEADERS);h.set("Access-Control-Allow-Origin",getAllowedOrigin(req,env)||env.ALLOWED_ORIGIN);h.set("Access-Control-Allow-Methods","GET, POST, DELETE, OPTIONS");h.set("Access-Control-Allow-Headers","Content-Type, Authorization");h.set("Vary","Origin");h.set("X-Content-Type-Options","nosniff");h.set("X-Frame-Options","DENY");h.set("Referrer-Policy","strict-origin-when-cross-origin");for(const[k,v]of Object.entries(extra))h.set(k,String(v));return new Response(JSON.stringify(data),{status,headers:h});}
function jsonError(m,s,r,e,x={}){return jsonResponse({error:m},s,r,e,x);}
function methodNotAllowed(a,r,e){return jsonError("Method not allowed.",405,r,e,{Allow:a.join(", ")});}
function normalizePaper(p){let tags=[];try{const x=JSON.parse(p.tags||"[]");if(Array.isArray(x))tags=x;}catch{}return{...p,tags,views:Number(p.views||0),word_count:Number(p.word_count||0),reading_time:Number(p.reading_time||1)};}
async function createUniqueSlug(db,title){const base=slugify(title);let c=base||`paper-${Date.now()}`,n=1;while(await db.prepare("SELECT id FROM papers WHERE slug=? LIMIT 1").bind(c).first()){n++;c=`${base}-${n}`;}return c;}
function slugify(v){return norm(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);}
function isValidSlug(v){return typeof v==="string"&&/^[a-z0-9](?:[a-z0-9-]{0,118}[a-z0-9])?$/.test(v);}
function createFtsQuery(q){const t=q.replace(/["']/g," ").split(/\s+/).map(x=>x.replace(/[^a-zA-Z0-9\u0900-\u097F_-]/g,"").trim()).filter(Boolean).slice(0,12);return t.length?t.map(x=>`"${x.replace(/"/g,'""')}"*`).join(" AND "):"";}
function countWords(t){const n=t.trim().replace(/\s+/g," ");return n?n.split(" ").length:0;}
function parsePositiveInteger(v,f){const n=Number.parseInt(v||"",10);return Number.isInteger(n)&&n>0?n:f;}
function norm(v){return typeof v==="string"?v.trim():"";}
function isPlainObject(v){return v!==null&&typeof v==="object"&&!Array.isArray(v);}
function getClientIp(r){return r.headers.get("CF-Connecting-IP")||r.headers.get("X-Forwarded-For")?.split(",")[0]?.trim()||"unknown";}
async function sha256(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function constantTimeEqual(a,b){const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let r=0;for(let i=0;i<x.length;i++)r|=x[i]^y[i];return r===0;}
function sanitizeErrorCode(e){return typeof e?.code==="string"?e.code:"PROVIDER_FAILED";}
async function logError(env,req,error,endpoint,provider){if(!env?.DB)return;try{await env.DB.prepare("INSERT INTO errors(timestamp,endpoint,message,provider,ip_hash) VALUES(CURRENT_TIMESTAMP,?,?,?,?)").bind(endpoint,String(error?.message||"Unknown error").replace(/Bearer\s+[A-Za-z0-9._~-]+/gi,"Bearer [REDACTED]").replace(/AIza[A-Za-z0-9_-]{20,}/g,"[REDACTED]").slice(0,2000),provider||"system",await sha256(getClientIp(req))).run();}catch{}}
